name: Coverage
run-name: Coverage
on: [push]
jobs:
  Coverage:
    runs-on: self-hosted
    steps:
      - run: echo "Job is running on a ${{ runner.os }} runner"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Restore previous coverage build files
        uses: actions/download-artifact@v4
        with:
          name: coverage-build-files
      - name: Files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build CMake project
        run: |
          cmake -S . -B build -DBUILD_TESTING=ON
          cmake --build build -j $([Environment]::ProcessorCount)
      - name: Run coverage
        run: |
          opencppcoverage --sources Source\**\ --modules build\Debug\** --export_type=html:coverage -- .\build\Debug\Tests.exe
      - name: Uploading coverage results
        uses: actions/upload-artifact@v4.3.3
        with:
          name: coverage-results
          path: coverage
      - name: Uploading coverage build files
        uses: actions/upload-artifact@v4.3.3
        with:
          name: coverage-build-files
          path: build