name: Tests
run-name: Tests
on: [push]
jobs:
  Tests:
    runs-on: self-hosted
    steps:
      - run: echo "Job is running on a ${{ runner.os }} runner"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Restore cached tests build files
        id: tests-build-files-restore
        uses: actions/cache/restore@v4
        with:
          path: build
          key: tests-build
      - name: Files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build CMake project
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build -j $([Environment]::ProcessorCount)
      - name: Run tests
        run: |
          cd build
          ctest --verbose -C Debug
      - name: Save tests build files
        id: tests-build-files-save
        uses: actions/cache/save@v4
        with:
          path: |
            build
          key: ${{ steps.tests-build-files-restore.outputs.cache-primary-key }}
